### ISSUE TITLE
Last token without new line won't get lexed

### ISSUE THREAD

**Issue by loislnessie** [jabney/tinylex#1]
Hi. Self-explanatory, I guess. When a file doesn't end with a new line, but with token, that token won't get lexed.

Thanks a lot!

**Comment by jabney** [comment]
Thanks for reporting this. I'll look into getting it fixed as soon as I'm able.

**Comment by jabney** [comment]
Finally fixed in [v0.7.3](https://github.com/jabney/tinylex/tree/v0.7.3)
